@startuml

class Account {
  + userName: String
  + password: String
  bool update()
}

class Person {
  + fullName: String
  + email: String
  + phone: String
  bool update()
}

class Admin {
  bool blockPost()
  bool blockUser()
  bool unBlockPost()
  bool unBlockUser()
}

class Member{
  + dateOfMembership: DateTime
  bool update()
  bool sendMessage()
  bool createPost()
  bool createGroup()
}

class Photographer {
  bool createScheduleConfirmation()
  bool postJob()
}

class Model {
  bool sendApplicationRequest()
}

class Customer {
  
}

class Job {
  + title: String
  + description: String
  + createdAt: DateTime
  + endTime: DateTime
  bool update()
}

class Application {
  + linkCV: String
  + userApplied: Member
  bool update()
}

class Task {
  + title: String
  + description: String
  + date: DateTime
  + startTime: DateTime
  + endTime: DateTime
  bool update()
}

class ScheduleConfirmation {
  + startTime: DateTime
  + endTime: DateTime
  + title: String
  + description: String
  + userConfirmed: Member
  bool accept()
  bool reject()
}

class ApplicationRequest {
  + userPostJob: Member
  + linkCV: String
  bool accept()
  bool reject()
}

class Message {
  + sendTo: Member[]
  + media: Media
  + body: String
  bool addMember()
}

class Notification {
  + createAt: DateTime
  + content: String
  void send()
}

class Post {
  + text: String
  + totalLikes: Number
  + totalShares: Number
  + images: Image[]
  bool update()
  bool delete()
}

class Comment {
  + body: String
  bool updateBody()
}

class Group {
  + name: String
  + description: String
  + members: Member[]
  bool addMember()
}

Person *-- Account
Person <|-- Admin
Person <|-- Member

Member <|-- Photographer
Member <|-- Model
Member <|-- Customer
Member "1..*"--"0..*" Group
Member "1"--"0..*" Post
Member "0..*"--"1..*" Message

Photographer "1"--"0..*" Job
Photographer "1"--"0..*" Task
Photographer "1"--"0..*" ScheduleConfirmation
Job "1"--"0..*" Application

Model "0..*"--"1..*" Task
Model "1"--"0..*" ApplicationRequest


Notification "*"<--"1" ScheduleConfirmation : creates
Notification "*"<--"1" ApplicationRequest: creates
Notification "*"<--"1" Message: creates
Notification "*"<--"1" Post: creates
Notification "*"<--"1" Comment: creates

@enduml
